### ISSUE TITLE
I can not install the theme.

### ISSUE THREAD

**Issue by ghost** [michidk/Aseprite-DarkFlat-Theme#3]
I tried in several ways to select the folder with the theme inside, but I can not select it, the version I am using is 1.2 installed by Steam. Detail, from what I researched it looks like it is mapped to a folder called "skins" but it does not exist in my files. The folder where I am putting the theme files is in "data / extensions / aseprite-theme" can this possibly be influencing something?

![1](https://user-images.githubusercontent.com/34857874/34438189-118778a0-ec8c-11e7-8354-8888e854a4ce.PNG)

![2](https://user-images.githubusercontent.com/34857874/34438197-1c82578e-ec8c-11e7-9aae-ef22545d6582.PNG)

If I am doing something wrong, please inform me with a very simple tutorial on how to do the installation procedure for themes.

I await your reply.

**Comment by michidk** [comment]
This theme won't work with the newer versions of Aseprite.
If you are still looking for a flat dark theme, you might want to check out the [Minimal Dark Theme](https://2dchaos.itch.io/minimal-dark-aseprite-theme).

**Comment by ghost** [comment]
😃Thank you so much.

________________________________
De: Michael Lohr <notifications@github.com>
Enviado: sexta-feira, 29 de dezembro de 2017 12:00:57
Para: michidk/Aseprite-DarkFlat-Theme
Cc: Teghit; Author
Assunto: Re: [michidk/Aseprite-DarkFlat-Theme] I can not install the theme. (#3)


This theme won't work with the newer versions of Aseprite.
If you are still looking for a flat dark theme, you might want to check out the Minimal Dark Theme<https://2dchaos.itch.io/minimal-dark-aseprite-theme>.
